name: scilabrl
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2022.9.24=h4653dfc_0
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.39.4=h76d750c_0
  - libzlib=1.2.13=h03a7124_4
  - ncurses=6.3=h07bb92c_1
  - openssl=3.0.5=h03a7124_2
  - pip=22.3=pyhd8ed1ab_0
  - python=3.8.13=hd3575e6_0_cpython
  - readline=8.1.2=h46ed386_0
  - setuptools=65.5.0=pyhd8ed1ab_0
  - sqlite=3.39.4=h2229b38_0
  - tk=8.6.12=he1e0b03_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - pip:
    - alembic==1.8.1
    - antlr4-python3-runtime==4.8
    - attrs==22.1.0
    - autopage==0.5.1
    - certifi==2022.9.24
    - cffi==1.15.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cliff==4.0.0
    - cloudpickle==2.0.0
    - cmaes==0.8.2
    - cmd2==2.4.2
    - colorlog==6.7.0
    - contourpy==1.0.5
    - cycler==0.11.0
    - cython==0.29.28
    - databricks-cli==0.17.3
    - docker==6.0.0
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - flask==2.2.2
    - fonttools==4.37.4
    - gitdb==4.0.9
    - gitpython==3.1.29
    - glfw==2.5.2
    - gunicorn==20.1.0
    - gym==0.21.0
    - hydra-core==1.1.2
    - idna==3.4
    - imageio==2.22.4
    - importlib-metadata==5.0.0
    - importlib-resources==5.2.3
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - joblib==1.1.0
    - kiwisolver==1.4.4
    - mako==1.2.3
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - mlflow==1.24.0
    - numpy==1.23.4
    - oauthlib==3.2.2
    - omegaconf==2.1.2
    - opencv-python-headless==4.5.5.64
    - optuna==2.10.0
    - packaging==21.3
    - pandas==1.5.1
    - pathtools==0.1.2
    - pbr==5.10.0
    - pillow==9.2.0
    - prettytable==3.4.1
    - prometheus-client==0.15.0
    - prometheus-flask-exporter==0.20.3
    - promise==2.3
    - protobuf==3.20.1
    - psutil==5.9.3
    - pycparser==2.21
    - pyjwt==2.6.0
    - pyparsing==3.0.9
    - pyperclip==1.8.2
    - python-dateutil==2.8.2
    - pytz==2022.5
    - pyyaml==6.0
    - querystring-parser==1.2.4
    - requests==2.28.1
    - scipy==1.9.3
    - sentry-sdk==1.9.10
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - six==1.16.0
    - smmap==5.0.0
    - sqlalchemy==1.4.42
    - sqlparse==0.4.3
    - stable-baselines3==1.1.0
    - stevedore==4.1.0
    - tabulate==0.9.0
    - tqdm==4.63.1
    - typing-extensions==4.4.0
    - urllib3==1.26.12
    - wandb==0.12.14
    - wcwidth==0.2.5
    - websocket-client==1.4.1
    - werkzeug==2.2.2
    - zipp==3.9.0
